create table if not exists public.sms_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  job_id uuid null references public.jobs(id) on delete set null,
  phone text not null,
  template text not null,
  body text not null default '',
  channel text not null default 'sms',
  provider text not null default 'twilio',
  status text not null default 'queued',
  provider_message_sid text null,
  error_code text null,
  error_message text null
);

create index if not exists sms_logs_created_at_idx on public.sms_logs (created_at desc);
create index if not exists sms_logs_job_id_idx on public.sms_logs (job_id);
create index if not exists sms_logs_provider_message_sid_idx on public.sms_logs (provider_message_sid);
